from typing import Literal

VIDEO_FPS = 30
VIDEO_CODEC = "libx264"
VIDEO_BITRATE = "6000k"

FADE_DURATION = 2

NORMALIZATION_TYPE: Literal["rms", "peak", "ebu"] = "ebu"
NORMALIZATION_TARGET_LEVEL = -18
NORMALIZATION_LOUDNESS_TARGET = 12
NORMALIZATION_AUDIO_CODEC = "aac"
NORMALIZATION_AUDIO_SAMPLE_RATE = 48000

ENTRIES_PER_FRAGMENT = 25
