from common.custom_types import Stage, STAGE_ONE

DEFAULT_CONFIG_FILE_NAME = "musicosa.config.toml"

# Global defaults
DEFAULT_ARTIFACTS_FOLDER = "artifacts"
DEFAULT_START_FROM_STAGE: Stage = STAGE_ONE
DEFAULT_STITCH_FINAL_VIDEO_FLAG = False
# Stage 1 defaults
DEFAULT_FORMS_FOLDER = "contestant_forms"
DEFAULT_VALID_TITLES_FILE = "titles.txt"
DEFAULT_CONTESTANT_NAME_COORDS = "F2"
DEFAULT_ENTRIES_DATA_COORDS = "C6:H6"
# Stage 4 defaults
DEFAULT_TEMPLATES_API_URL = "http://localhost:3000/templates"
DEFAULT_PRESENTATIONS_API_URL = "http://localhost:3000/presentations"
DEFAULT_GENERATION_RETRY_ATTEMPTS = 3
DEFAULT_OVERWRITE_TEMPLATES = True
DEFAULT_OVERWRITE_PRESENTATIONS = True
# Stage 5 defaults
DEFAULT_STAGE_5_QUIET_FFMPEG = True
# Stage 6 defaults
DEFAULT_VIDEO_BITS_FOLDER = f"{DEFAULT_ARTIFACTS_FOLDER}/video_bits_folder"
DEFAULT_OVERWRITE_VIDEO_BITS = False
DEFAULT_FINAL_VIDEO_NAME = "musicosa-final"
DEFAULT_PRESENTATION_DURATION = 5
DEFAULT_TRANSITION_DURATION = 3
DEFAULT_TRANSITION_TYPE = "fade"
DEFAULT_STAGE_6_QUIET_FFMPEG = True
DEFAULT_QUIET_FFMPEG_FINAL_VIDEO = True
