VIDEO_TIMESTAMP_SEPARATOR = "-"
VIDEO_TIMESTAMP_TIME_SEPARATOR = ":"

TEMPLATE_IMG_FORMAT = "png"
PRESENTATION_IMG_FILE_SUFFIX = "PRESENTATION"
VIDEO_FORMAT = "mp4"

VIDEOCLIPS_OVERRIDE_DURATION_LIMIT = -1
