DEFAULT_TEMPLATES_API_URL = "http://localhost:3000/templates"
DEFAULT_PRESENTATIONS_API_URL = "http://localhost:3000/presentations"
DEFAULT_ARTIFACTS_FOLDER = "../artifacts"
DEFAULT_GENERATE_PRESENTATIONS = False
DEFAULT_GENERATION_RETRY_ATTEMPTS = 3
DEFAULT_OVERWRITE_TEMPLATES = True
DEFAULT_OVERWRITE_PRESENTATIONS = True
