start_from = 1
artifacts_folder = "artifacts"

[stage_1]
award_forms_folder = "award_forms"

[stage_4]
api_url = "http://localhost:3000/templates"
gen_retry_attempts = 3
overwrite_templates = true

[stage_5]
quiet_ffmpeg = true

[stage_6]
video_bits_folder = "artifacts/video_bits"
overwrite_video_bits = true
quiet_ffmpeg = true