start_from = 1
artifacts_folder = "artifacts"
stitch_final_video = true

[stage_1]
award_forms_folder = "award_forms"

[stage_4]
templates_api_url = "http://localhost:3000/templates"
presentations_api_url = "http://localhost:3000/presentations"
gen_retry_attempts = 3
overwrite_templates = true
overwrite_presentations = true

[stage_5]
quiet_ffmpeg = true

[stage_6]
video_bits_folder = "artifacts/video_bits"
overwrite_video_bits = true
presentation_duration = 5
transition_duration = 3
transition_type = "fade"
quiet_ffmpeg = true
quiet_ffmpeg_final_video = true