start_from = 1
artifacts_folder = "artifacts"

[stage_1]
csv_forms_folder = "contestant_forms"
valid_titles_file = "titles.txt"

[stage_4]
api_url = "http://localhost:3000/templates"
gen_retry_attempts = 3
overwrite_templates = true

[stage_5]
quiet_ffmpeg = true

[stage_6]
video_bits_folder = "artifacts/video_bits"
overwrite_video_bits = true
stitch_final_video = false
final_video_name = "musicosa-5th-edition"
quiet_ffmpeg = true
quiet_ffmpeg_final_video = false